version: "3"
services:
  task-service:
    container_name: task-service
    image: olacodes/task-service
    ports:
      - "8082:8082"
    depends_on:
      - task-service-db
      - eureka-server
      - api-gateway
    networks:
      - postgres
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-service:
    container_name: auth-service
    image: olacodes/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - auth-service-db
      - eureka-server
      - api-gateway
    networks:
      - postgres
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka-server:
    container_name: eureka-server
    image: olacodes/eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring

  api-gateway:
    container_name: api-gateway
    image: olacodes/api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  task-service-db:
    container_name: task-service-db
    image: postgres:11.16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=task-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - postgres

  auth-service-db:
    image: postgres:11.16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
