apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deploy
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      name: auth-service
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: olacodes/auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
#      restartPolicy: Always
